<?php
$plugin['12_8_4_4_stacked'] = array(
  'title' => t('Top row 12, three columns 8-4-4'),
  'icon' => '12_8_4_4_stacked.png',
  'theme' => '12_8_4_4_stacked',
  'category'  => 'Latto - multiple rows, three columns',
  'regions' => array(
    'grid_12_top_left' => t('Top content'),
    'grid_8_left' => t('Left content'),
    'grid_4_center_right' => t('Right inner sidebar'),
    'grid_4_right' => t('Right sidebar'),
  ),
);
