<?php
$plugin['bottom_full_8_8_stacked'] = array(
  'title' => t('two columns 8-8, bottom row full'),
  'icon' => 'bottom_full_8_8_stacked.png',
  'theme' => 'bottom_full_8_8_stacked',
  'category'  => 'Latto - multiple rows, two columns',
  'regions' => array(
    'grid_8_left' => t('Left content'),
    'grid_8_right' => t('Right content'),
    'grid_16_bottom_full' => t('Bottom content'),
  ),
);
