<?php
$plugin['stacked_8_4_4_reverse'] = array(
  'title' => t('Stacked, three columns 10-3-3'),
  'icon' => 'stacked_8_4_4_reverse.png',
  'theme' => 'stacked_8_4_4_reverse',
  'category'  => 'Latto - multiple rows, three columns',
  'regions' => array(
    'grid_12_top_left' => t('Top left content'),
    'grid_4_right' => t('Top right sidebar'),
    'grid_8_left' => t('left content'), 
    'grid_4_center_right' => t('Right center content'),
    'grid_4_right' => t('Right content'),
  ),
);
