<?php
$plugin['stacked_8_4_4_reverse'] = array(
  'title' => t('Stacked, three columns 8-4-4'),
  'icon' => 'stacked_8_4_4_reverse.png',
  'theme' => 'stacked_8_4_4_reverse',
  'category'  => 'Latto - multiple rows, three columns',
  'regions' => array(
    'grid_16_top_full' => t('Top full'),
    'grid_12_left' => t('Left sidebar'),
    'grid_4_right' => t('Right sidebar'), 
    'grid_8_bottom_left' => t('Bottom left'),
    'grid_4_bottom_center_right' => t('Bottom center right'),
    'grid_4_bottom_right' => t('Bottom right'),
  ),
);
